zuul:
  routes: #路由的配置是个Map，可以配置多个
    token:  #token结尾的请求，都转发到http://localhost:9090认证服务器地址
      url:  http://localhost:9090
    order:  #order结尾的请求，都转发到http://localhost:9080 顶单服务
      url:  http://localhost:9080
  sensitive-headers:  null  #设置敏感头设置为空，Authorization等请求头的请求，都往后转发

spring:
  application:
    name: auth-server
  datasource:
    url: jdbc:mysql://localhost:3306/security?serverTimezone=UTC&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true

server:
  port: 9070