zuul:
  routes: #路由的配置是个Map，可以配置多个
    token:  #token结尾的请求，都转发到http://localhost:9090认证服务器地址
      url:  http://localhost:9090
    order:  #order结尾的请求，都转发到http://localhost:9080 订单服务
      url:  http://localhost:9080
  sensitive-headers:  null  #设置敏感头设置为空，Authorization等请求头的请求，都往后转发


server:
  port: 9070