spring:
  application:
    name: user-api
  datasource:
    url: jdbc:mysql://localhost:3306/security?serverTimezone=UTC&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true