spring:
  application:
    name: user-api
  datasource:
    url: jdbc:mysql://localhost:3306/imooc-security?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      generate-ddl: true
      show-sql: true
server:
  port: 8081
