zuul:
  routes:
    token:
      url: http://localhost:9090
    order:
      url: http://localhost:9080
  sensitive-headers:
  ratelimit:
    enabled: true
    repository: JPA
    default-policy-list:
    - limit: 2 
      quota: 1 
      refresh-interval: 3
      type:
        - url 
        - httpmethod
spring:
  application:
    name: gateway
  datasource:
    url: jdbc:mysql://localhost:3306/security?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    show-sql: true
    
server:
  port: 9070     