server:
  port: 9080
spring:
  application:
    name: order

security:
  oauth2:
    resource:
      jwt:
        key-uri: http://auth.nb.com:9090/oauth/token_key
        key-value: 123456
    client:
      client-id: orderService
      client-secret: 123456
