server:
  port: 9080
spring:
  application:
    name: order
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719   #机器上启动一个 Http Server，该 Server 会与 Sentinel 控制台做交互

security:
  oauth2:
    resource:
      jwt:
        key-uri: http://auth.nb.com:9090/oauth/token_key
        key-value: 123456
    client:
      client-id: orderService
      client-secret: 123456
